### ISSUE TITLE
Announce plugin on mailing list

### ISSUE THREAD

**Issue by thibaultcha** [foodora/kong-plugin-jwt-crafter#2]
Hello!

Good job on the plugin! We are happy to see members of the community stepping forward and publishing Kong plugins on Luarocks :)

As of now, we don't offer you yet a way to advertise your plugin on https://getkong.org/plugins, but are planning to in the future. In the meantime, feel free to publish an announcement on the [Kong Mailing List](https://groups.google.com/forum/#!forum/konglayer), as I am sure it will give you some exposition and peak the interest of some Kong users out there. In fact, I have definitely seen seveal requests for such a feature already :)

```
[ANN] Community Plugin - kong-plugin-jwt-crafter 1.0
```

Just a suggestion :)

Best,
Thibault

**Comment by vvondra** [comment]
Done, I wanted to merge building tests on Travis first in #1  :)
